name: Deploy Images to GHCR

on:
  release:
    types: [published]
#  push:
#    branches:
#      - main
#  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: './Store'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
#          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Log in to the Container registry
      #   uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: newbenji/awscli-kubectl
      
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
#      - name: 'Build Inventory Image'
#        run: |
#          docker build . --tag ghcr.io/newbenji/aws-cli:latest
#          docker push ghcr.io/newbenji/aws-cli:latest
